---
type: array
shape:
  type: object
  shape:
    fields:
    - name: relation
      type: string
      options:
      - Parent
      - Sibling
      - Spouse
    - name: name
      type: string
    - name: date_of_birth
      type: date
