---
type: object
shape:
  fields:
  - name: nicknames
    type: array
    shape:
      type: string

  - name: permissions
    type: array
    shape:
      type: string
      options:
      - can_make_coffee
      - can_drink_coffee
      - can_discuss_coffee

  - name: family
    type: array
    shape:
      type: object
      shape:
        fields:
        - name: relation
          type: string
          options:
          - Parent
          - Sibling
          - Spouse
        - name: name
          type: string
        - name: date_of_birth
          type: date

  - name: extended_family
    type: array
    focus:
    - name
    - estranged
    shape:
      type: object
      shape:
        fields:
        - name: relation
          type: string
          options:
          - Cousin
          - Aunt
          - Uncle
        - name: name
          type: string
        - name: date_of_birth
          type: date
        - name: estranged
          type: boolean
